swiftmailer:
    #url: '%env(MAILER_URL)%'
    transport: smtp
    host: 'smtp.ionos.fr'
    port: '587'
    username: 'noreply-cocovoit@lab.kelbert.fr'
    password: 'Qn7KTnfWekX9iaS'
    encryption: tls
    auth_mode: login

    spool: { type: 'memory' }
