swiftmailer:
    transport: smtp
    host: '%env(resolve:MAIL_HOST)%'
    port: '%env(resolve:MAIL_PORT)%'
    username: '%env(resolve:MAIL_USERNAME)%'
    password: '%env(resolve:MAIL_PASSWORD)%'
    encryption: '%env(resolve:MAIL_ENCRYPTION)%'
    auth_mode: login

    spool: { type: 'memory' }
