swiftmailer:
    #url: '%env(MAILER_URL)%'
    host: 'smtp.1and1.com'
    port: '25'
    username: 'noreply-cocovoit@lab.kelbert.fr'
    password: 'Qn7KTnfWekX9iaS'
    encryption: null
    auth_mode: null

    spool: { type: 'memory' }
